# Generated by Django 5.2.7 on 2025-11-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_sectionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='open_time',
            field=models.DateTimeField(blank=True, help_text='Time when the survey opens for students. If not set, survey opens immediately when published.', null=True),
        ),
    ]
