# Generated by Django 5.2.7 on 2025-11-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_temporarypasswordcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the student account has been verified by a teacher'),
        ),
    ]
