# Generated by Django 5.2.7 on 2025-11-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Surveys remain hidden from students until published.'),
        ),
    ]









